# MATRICES

   ### Computations with matrices.

## To create a Matrix

The simple way to create a matrix is to create a **list of list**. It is called as **Nested List**.

In [1]:
M1 = [[1, 2, 3],
      [4, 5, 6]
     ]
print(M1)

[[1, 2, 3], [4, 5, 6]]


We can type all kinds of data types in a matrix. Characters within `" "`, floating points and integers.

In [2]:
M2 = [[4, 5, 6],
      ["a", 1.56625, 75],
      [9, 5.699, 8]
     ]
print(M2)
type(M2)

[[4, 5, 6], ['a', 1.56625, 75], [9, 5.699, 8]]


list

The above methods do create matrices. But for mathematical purposes and ease, we use a package called "NumPy" which can do all the matrix operaions.

## Numpy

NumPy’s main object is the homogeneous multidimensional array, along with a large collection of high-level mathematical functions to operate on these arrays. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers.

In [3]:
import numpy as np  

We import **NumPy** using the above code and add prefix `np.` before the operation command. 

Note:We add `np.` since we have imported it as **`np`**.

If you use the command `import numpy as python`, use **`python`** as a suffix.

### To create a matrix using NumPy

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])#, dtype = complex)
A           # Displays the matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
print(A)       # We can use this command as well.
print(type(A)) # Gives the type of matrix A
print(A.dtype) # Gives the datatype of elments of A.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int32


* Change one element in the matrix. For example, use $5.0$ instead of $5$ and note the difference is the resulting outputs.

NumPy’s array class is called `ndarray`. It is also known by the alias `array`.

## Sympy

**SymPy** is a Python library for symbolic mathematics. It aims to become a full-featured computer algebra system (CAS) while keeping the code as simple as possible in order to be comprehensible and easily extensible. SymPy is written entirely in Python. SymPy only depends on `mpmath`, a pure Python library for arbitrary floating point arithmetic, making it easy to use.

In [6]:
import sympy as sp

We import SymPy using the above code and add prefix `sp.` before the operation command.

In [7]:
A = sp.Matrix([[1, 2, 3], [6, 7, 8], [4, 0, 5]])
A

Matrix([
[1, 2, 3],
[6, 7, 8],
[4, 0, 5]])

Suppose we use the code `from sympy import *` to import the module/package, we need not use any prefix, like `sp.`.

We can also use `mpmath` or `math` modules to do the mathematical operations. 

There are many libraries as like mentioned above for mathematical computation. The commands might vary sometimes. Go through the documentation for of the specific packages/modules to know more.

`Numpy` : https://numpy.org

`Sympy` : https://www.sympy.org/en/index.html

`math`  : https://docs.python.org/3/library/math.html

`mpmath`: http://mpmath.org/

We shall use only **NumPy** for all the computation. 

### To create different types of matrices using Numpy

##### Identity matrix of order $n$

In [8]:
import numpy as np
I2 = np.identity(2)
print("Identity matrix of order 2 : \n", I2)

Identity matrix of order 2 : 
 [[1. 0.]
 [0. 1.]]


In [9]:
I3 = np.identity(3, dtype = int)
print("Identity matrix of order 3 : \n", I3) 
I3.dtype

Identity matrix of order 3 : 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


dtype('int32')

The *datatype* expected is mentioned to be `int` (Integer) in the second example. Observe the difference. `dtype` will be a `float` by default.

##### Zero matrix

In [10]:
z1 = np.zeros(5)           # Gives a row matrix of 5 elements (Zeros)
print("Matrix Z1 : \n", z1) 
  
z2 = np.zeros((2, 2))      #Gives a 2x2 matix with zeros
print("\nMatrix Z2 : \n", z2) 
  
z3 = np.zeros([3, 3]) 
print("\nMatrix Z3 : \n", z3) 

z4 = np.zeros([3, 5]) 
print("\nMatrix Z4 : \n", z4) 

Matrix Z1 : 
 [0. 0. 0. 0. 0.]

Matrix Z2 : 
 [[0. 0.]
 [0. 0.]]

Matrix Z3 : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matrix Z4 : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


##### We can also create zero martrix using a 'for loop'

In [11]:
n = int(input("No. of Rows: "))
m = int(input("No. of Columns: "))
Z1 = [ [ 0 for i in range(m) ] for j in range(n) ]
print(Z1)
type(Z1)

No. of Rows: 5
No. of Columns: 2
[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]


list

Note : We are not using `numpy` here. Hence the type of matrix results in **list**.

##### Unit matrix

In [12]:
d = np.ones([3, 5])       # Create a unit matrix of order 3x5. datatype by default is "float"
print("\nMatrix c : \n", d)


Matrix c : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Create a unit matrix of order 3x5 and datatype as `int`

In [13]:
d = np.ones([3, 5], dtype = 'int') 
print("\nMatrix c : \n", d)


Matrix c : 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


##### Create a Random matrix

To create a random matrix, use the command `np.random.rand(m, n)` which creates a (m x n) matrix.

In [14]:
r = np.random.rand(3, 5) 
print("Matrix R : \n", r)

Matrix R : 
 [[0.74084473 0.28147657 0.48713722 0.50727886 0.61491337]
 [0.87325053 0.89240994 0.01774895 0.91174949 0.55174136]
 [0.62652921 0.01066252 0.32385252 0.95863495 0.91267847]]


In [15]:
r1 = np.random.randint(100, size = (4, 8)) 
print("\nMatrix R1 : \n", r1)


Matrix R1 : 
 [[44 44 30 70 63 48 67 68]
 [ 7 86 96 97 26 89 81 64]
 [63 42 93 73 70  0 11 77]
 [33 37  2 58  0 13 39 71]]


* `r` has command `rand(m, n)`, creates a mxn matrix where each elemnt is between $0$ and $1$.
* `r1` has command `randint(a, size = (m, n))`, creates a mxn matrix where each element is lessthan a. ie., $\forall r_{ij}$ in $R1, r_{ij}$ $\in$ $\mathbb({Z}^{+})$  and $< a $
* Execute the command once and note the vlaues. Execute again and observe.

In [16]:
A = (np.arange(4))
print('A =', A)

B = np.arange(12).reshape(3, 4)
print('B =', B)

A = [0 1 2 3]
B = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


`A` gives a row matrix from 0 to 3. 

**Note:** Indexing in python starts from $0$ and for a range of length $n$, the value stops at $n-1$. We can observe that last element of `A` is $3$ for a given length of $4$. Similarly in Matrix `B`.

The Linear Algebra submodule of NumPy that offers various methods to apply linear algebra on any numpy array. Use use the command `np.linalg.<operation>`, where `np.linalg` is the submodule used.

##### To find the Determinant of $A$. ($\det{A}$)

First define the matrix using `np.array([])`. Use `np.linalg.det()` to find the matrix.

In [17]:
A = np.array([[1, 2, 1],
             [4, -1, 1],
             [1, 6, 9]])
DetA = np.linalg.det(A)
DetA

-60.000000000000036

In [18]:
# The determinant value is a float. To round it to the nearest integer,
print(np.round(DetA))

-60.0


##### Inverse of a matrix.

Command : `np.linalg.inv()`

In [19]:
InvA = np.linalg.inv(A)
print(InvA)

[[ 0.25        0.2        -0.05      ]
 [ 0.58333333 -0.13333333 -0.05      ]
 [-0.41666667  0.06666667  0.15      ]]


The NumPy module gives a float as an output while finding the inverse. If we want fractions as the result we use `sympy` to find the *inverse*. We can use the following code to find the inverse using `SymPy`.

In [20]:
import sympy as sp
A1 = sp.Matrix([[1, 2, 1],
     [4, -1, 1],
     [1, 6, 9]])
b1 = A1.inv()
b1

Matrix([
[  1/4,   1/5, -1/20],
[ 7/12, -2/15, -1/20],
[-5/12,  1/15,  3/20]])

Observe that `numpy` and `sympy` commands are different for the same function, ie., `inv`. In `numpy` we specify the matrix in the command, while in `sympy`, its just an extension after the given matrix.

##### Transpose of a matrix using NumPy

In [21]:
import numpy as np
AT = np.transpose(A)
AT

array([[ 1,  4,  1],
       [ 2, -1,  6],
       [ 1,  1,  9]])

`np.size` gives the total number of elements in the Matrix 

In [22]:
size = np.size(A)
print(size)

9


`np.shape` gives the dimension of the Matrix. ie., (`no. of rows`, `no. of columns`)

In [23]:
order = np.shape(A)
order

(3, 3)

To find the rank of a matrix, use the command `np.linalg.matrix_rank(A)`. This command just gives the rank of the matrix but not any reduced form of the matrix.

In [24]:
rank = np.linalg.matrix_rank(A)
rank

3

To find eigenvalues and eigenvectors of a matrix, use `np.linalg.eigvals( )` to find the eigen values and `np.linalg.eig( )` to find the corresponding eigen vectors.

In [25]:
eig = np.linalg.eigvals(A)
eig

array([-3.,  2., 10.])

In [26]:
eig1 = np.linalg.eig(A)
eig1

(array([-3.,  2., 10.]),
 array([[ 0.32770634, -0.57735027,  0.14002801],
        [-0.85567768, -0.57735027,  0.14002801],
        [ 0.40052998,  0.57735027,  0.98019606]]))

In [27]:
V = np.transpose(np.array([[ 0.32770634, -0.57735027,  0.14002801],
        [-0.85567768, -0.57735027,  0.14002801],
        [ 0.40052998,  0.57735027,  0.98019606]]))
V1 = V[0, :]
V2 = V[1, :]
V3 = V[2, :]
V

array([[ 0.32770634, -0.85567768,  0.40052998],
       [-0.57735027, -0.57735027,  0.57735027],
       [ 0.14002801,  0.14002801,  0.98019606]])

In [28]:
V1

array([ 0.32770634, -0.85567768,  0.40052998])

In [29]:
-3*V1

array([-0.98311902,  2.56703304, -1.20158994])

In [30]:
A.dot(np.transpose(V1))

array([-0.98311904,  2.56703302, -1.20158992])

In [31]:
np.tril(A)

array([[ 1,  0,  0],
       [ 4, -1,  0],
       [ 1,  6,  9]])

In [32]:
np.triu(A)

array([[ 1,  2,  1],
       [ 0, -1,  1],
       [ 0,  0,  9]])

### Some manupulations on a matrix

In [33]:
np.min(A)  # Finds the smallest element in a matrix

-1

In [34]:
np.max(A)  # Finds the largest element in a matrix

9

In [35]:
len(A)

3

The length of the matrix gives result as $3$ since its a **Nested array**. Each row is an individual array and $3$ arrays form $3$ rows. Meaning each row is considered as one element. 

But it is not the same when we use `sympy` to create the matrix. Because the matrix formed is not a nested array. Try it!

In [36]:
len(A[0])     #Gives number of elements in the first row, which indeed tells us the number of columns in the matrix.

3

To find the sum of all elements in a given matrix

In [37]:
Sum = np.sum(A)
Sum

24

To find the product of all elements in a given matrix

In [38]:
prod = np.prod(A)
prod

-432

To find the Trace of a matrix

In [39]:
np.trace(A)

9

##### Operations between two matrices

In [40]:
A = np.array([[1, 2, 1],
              [4, -1, 1],
              [1, 6, 9]
             ])
B = np.array([[-8, 2, 1],
             [4, -1, 3],
             [4, 7, 9]
             ])
print(A)
print(B)

[[ 1  2  1]
 [ 4 -1  1]
 [ 1  6  9]]
[[-8  2  1]
 [ 4 -1  3]
 [ 4  7  9]]


In [41]:
#Element wise addition
C = A + B
C

array([[-7,  4,  2],
       [ 8, -2,  4],
       [ 5, 13, 18]])

In [42]:
#Element wise subtraction
D = A - B
D

array([[ 9,  0,  0],
       [ 0,  0, -2],
       [-3, -1,  0]])

In [43]:
#Element wise multiplication
E = A*B
E

array([[-8,  4,  1],
       [16,  1,  3],
       [ 4, 42, 81]])

`A*B` results in **element wise multiplication**.

`A.dot(B)` results in **matrix multiplication**.

In [44]:
# Matrix multiplication
E1 = A.dot(B)
E1

array([[  4,   7,  16],
       [-32,  16,  10],
       [ 52,  59, 100]])

In [45]:
#Element wise division
F = A/B
F

array([[-0.125     ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  0.33333333],
       [ 0.25      ,  0.85714286,  1.        ]])

In [46]:
# Scalar Multiplication
G = 2*A
G

array([[ 2,  4,  2],
       [ 8, -2,  2],
       [ 2, 12, 18]])

Square of a matrix can be found using either `M.dot(M)` or `np.linalg.matrix_power(M,2)` where $M$ is a matrix.

For calculating higher powers, it is better use `np.linalg.matrix_power(M,n)`, where $n$ is the power to which the matrix needs to be raised.

In [47]:
H1 = A.dot(A)
H1

array([[10,  6, 12],
       [ 1, 15, 12],
       [34, 50, 88]])

In [48]:
H2 = np.linalg.matrix_power(A,2)
H2

array([[10,  6, 12],
       [ 1, 15, 12],
       [34, 50, 88]])

H3 and H4 are equal.

`x**2` where $x$ is any scalar will give the square of $x$, $x^2$. If $M$ is a Matrix, `M**2` will **not** result in square of matrix $M^2$, but will **result in square of elements of the matrix**. 

$ie. M_{ij}$\*\*2 $= m_{ij}^2$

We can also use `np.square()` to find the square of elements of matrix.

In [49]:
H3 = A**2
H3

array([[ 1,  4,  1],
       [16,  1,  1],
       [ 1, 36, 81]], dtype=int32)

In [50]:
H4 = np.square(A)
H4

array([[ 1,  4,  1],
       [16,  1,  1],
       [ 1, 36, 81]], dtype=int32)

##### To access elements in an array

In [51]:
A2 = [1, 2, 3, 5, 9, 13]

In [52]:
len(A2)      # There are 6 elements in the above array.

6

In [53]:
A2[1]

2

`A2[1]` gives the second element of the array since **indexing in python starts from $0$**. 

In [54]:
A2[0]     

1

This results in first element of the array. The index of the first element is 0(zero).

To find the last element, the index is $n-1$ where $n$ is the length of the array. We can use either of the following commands.

In [55]:
A2[-1]

13

In [56]:
A2[(len(A2)-1)]

13

In [57]:
A2[:]     #Gives the entire array

[1, 2, 3, 5, 9, 13]

Suppose we have a nested array.

In [58]:
A

array([[ 1,  2,  1],
       [ 4, -1,  1],
       [ 1,  6,  9]])

In [59]:
len(A)    # Already explained

3

In [60]:
A[0]      # Gives the first element, in this case, its the first row

array([1, 2, 1])

In `A[][]`, the first bracket will refer to the **row/s** and the second bracket will refer to **column/s**. Also you can use `A[m, n]` where `m` represents rows and `n` represents columns.

For the given matrix, `A[1][0]` or `A[1, 0]` will give the element in **2nd row, 1st column**.


In [61]:
A[1][0]

4

In [62]:
A[1, 0]

4

In [63]:
A[1][len(A)-1]

1

In [64]:
A[:]     # Gives all the elements in the matrix

array([[ 1,  2,  1],
       [ 4, -1,  1],
       [ 1,  6,  9]])

In [65]:
A[0, :]    # First row, all columns

array([1, 2, 1])

In [66]:
A[:1,]     # First row of all the columns

array([[1, 2, 1]])

In [67]:
A[:,0]     # Gives elements in all the rows of the 1st column..

array([1, 4, 1])

In [68]:
A[0:3, 0:2]      # Gives the elements from 1-3 rows and 1-2 columns

array([[ 1,  2],
       [ 4, -1],
       [ 1,  6]])

`A[0:3, 0:2]` chooses elements from 1st row (index starts from 0) upto 3rd row ( We already know range(n) means n-1 elements, here 3 represents the index 2, which is 3rd row). Similarly for columns. 0:2 implies index 0 to index 1 by python, which are the first and second columns.

In [69]:
A[1:3, :]

array([[ 4, -1,  1],
       [ 1,  6,  9]])

In [70]:
A[2][2]

9

## Exercise Problems

1. Create matrices $A = \begin{bmatrix}5 & -3 & 2\\ -6 & 10 & 7\\ 2 & 4 & 1 \end{bmatrix}$ and  $B = \begin{bmatrix}1 & 3 & -2\\ 8 & 2 & 1\\ 1 & -1 & 6 \end{bmatrix}$

In [71]:
import numpy as np
A = np.array([[5, -3, 2],
             [-6, 10, 7],
              [2, 4, 1]
             ])
print("Matrix A is \n", A)

B = np.array([[1, 3, -2],
             [8, 2, 1],
              [1, -1, 6]
             ])
print("\n Matrix B is \n", B)

Matrix A is 
 [[ 5 -3  2]
 [-6 10  7]
 [ 2  4  1]]

 Matrix B is 
 [[ 1  3 -2]
 [ 8  2  1]
 [ 1 -1  6]]


2. Create a matrix $P$ of order 3x4 by taking random elements and then find transpose of $P$.

In [72]:
P = np.random.randint(30, size = (3, 4))
print("Matrix P is: \n", P)
PT = np.transpose(P)
print("\nMatrix PT is: \n", PT)

Matrix P is: 
 [[ 6 11 22 28]
 [ 2 16 28  1]
 [16 23 23 27]]

Matrix PT is: 
 [[ 6  2 16]
 [11 16 23]
 [22 28 23]
 [28  1 27]]


3. Create matrices p = $\begin{bmatrix} 1 & 5 & 6\\ 7 & 8 & 10\\ 0 & 1 & 5 \end{bmatrix} $ and q = $\begin{bmatrix} 7 & 8 & 10\\ 15 & 1 & 2\\ 3 & 7 & 5 \end{bmatrix}$

Compute
(i) $p + q$
(ii) $pq$
(iii) $p - q$ 
(iv) $p^{-1}$
(v) $p^2$
(vi) $3p + 4q$ (vii) $5p^2 + 7q^2$
(viii) $p * q$(elementwise multiplication)
(ix) $p' + q'$
(x) $3pq' + 5qp'$

In [73]:
p = np.array([[1, 5, 6],
              [7, 8, 10],
              [0, 1, 5]
             ])
q = np.array([[7, 8, 10],
              [15, 1, 2],
              [3, 7, 5]
             ])
print(p,)
print("\n", q)

[[ 1  5  6]
 [ 7  8 10]
 [ 0  1  5]]

 [[ 7  8 10]
 [15  1  2]
 [ 3  7  5]]


In [74]:
p+q

array([[ 8, 13, 16],
       [22,  9, 12],
       [ 3,  8, 10]])

In [75]:
p.dot(q)

array([[100,  55,  50],
       [199, 134, 136],
       [ 30,  36,  27]])

In [76]:
p-q

array([[-6, -3, -4],
       [-8,  7,  8],
       [-3, -6,  0]])

In [77]:
np.linalg.inv(p)

array([[-0.29126214,  0.18446602, -0.01941748],
       [ 0.33980583, -0.04854369, -0.31067961],
       [-0.06796117,  0.00970874,  0.26213592]])

In [78]:
p.dot(p)

array([[ 36,  51,  86],
       [ 63, 109, 172],
       [  7,  13,  35]])

In [79]:
3*p + 4*q

array([[31, 47, 58],
       [81, 28, 38],
       [12, 31, 35]])

In [80]:
5*(p.dot(p)) + 7*q.dot(q)

array([[1573, 1193, 1382],
       [1197, 1490, 1994],
       [1022,  527,  658]])

In [81]:
p*q

array([[  7,  40,  60],
       [105,   8,  20],
       [  0,   7,  25]])

In [82]:
np.transpose(p) + np.transpose(q)

array([[ 8, 22,  3],
       [13,  9,  8],
       [16, 12, 10]])

In [83]:
3*p.dot(np.transpose(q)) + 5*q.dot(np.transpose(p))

array([[ 856, 1161,  494],
       [ 799, 1064,  436],
       [ 514,  668,  256]])

4. For the matrices $A$ and $B$, find
(i) $a_{23}$
(ii) $b_{32}$
(iii) $row_{1}(A)$
(iv) $col_{1}(A)$
(v) $row_{2}(B)$

In [84]:
A = np.array([[5, -3, 2],
              [-6, 10, 7],
              [2, 4, 10]
             ], dtype = "float64")
B = np.array([[4*2, 2/30],
              [1/205, 5-7.8],
              [0.0001, (9+80/50)]
             ], dtype = "float64")

In [85]:
A

array([[ 5., -3.,  2.],
       [-6., 10.,  7.],
       [ 2.,  4., 10.]])

In [86]:
B

array([[ 8.00000000e+00,  6.66666667e-02],
       [ 4.87804878e-03, -2.80000000e+00],
       [ 1.00000000e-04,  1.06000000e+01]])

In [87]:
# i)
A[1,2]

7.0

In [88]:
# ii)
B[2, 1]

10.6

In [89]:
# iii)
A[0]

array([ 5., -3.,  2.])

In [90]:
# iv)
A[:, 0]

array([ 5., -6.,  2.])

In [91]:
# v)
B[1]

array([ 0.00487805, -2.8       ])

5. Compute the following if possible, otherwise give reason why its
not possible
(i) $A * C$
(ii) $A.*C$
(iii) $A + C'$
(iv) $B * A - C' * A$
(v) $(2 + C - 6 * A') * B'$ 
(vi) $A * C - C * A$
(vii) $A * A' + C' * C$

In [92]:
A = np.array([[1, 1/2],
              [1/3, 1/4],
              [1/5, 1/6]
             ])
B = np.array([5, 2])
C = np.array([[4, 4/5, 10/7],
              [1, 5, 6]
             ])

In [93]:
# i)
A.dot(C)

array([[4.5       , 3.3       , 4.42857143],
       [1.58333333, 1.51666667, 1.97619048],
       [0.96666667, 0.99333333, 1.28571429]])

In [94]:
# ii)
A**C     # Read the error and you can come to conclusion easily.

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [95]:
# iii)
A + np.transpose(C)

array([[5.        , 1.5       ],
       [1.13333333, 5.25      ],
       [1.62857143, 6.16666667]])

In [96]:
# iv)
(2 + C - 6*np.transpose(A))#dot(np.transpose(B))

array([[0.        , 0.8       , 2.22857143],
       [0.        , 5.5       , 7.        ]])

In [97]:
# v)
(2 + C - 6*np.transpose(A)).dot(np.transpose(B))
# Go through the dim of matrices for the reason

ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [98]:
# v)a. Why does this work?
np.transpose(B).dot((2 + C - 6*np.transpose(A)))

array([ 0.        , 15.        , 25.14285714])

In [99]:
# vi)
A.dot(C) - C.dot(A)

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [100]:
# vii)
A.dot(np.transpose(A)) + np.transpose(C).dot(C)

array([[18.25      ,  8.65833333, 11.99761905],
       [ 8.65833333, 25.81361111, 31.25119048],
       [11.99761905, 31.25119048, 38.1085941 ]])

6. Create
(i) 5 x 4 unit matrix.
(ii) 10 x 11 zero matrix.
(iii) 14 x 14 diagonal matrix.
(iv) 15 x 15 random matrix.
(v) 16 x 16 scalar matrix.
(vi) 6 x 6 identity matrix.
(vii) 6 x 6 tridiagonal matrix.
(viii) 4 x 4 diagonal matrix with diagonal elements equal to five.

In [101]:
# iii)
d = np.random.randint(14, size = (14))
np.diag(d)

array([[ 4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11]])

In [102]:
# iv)
np.random.randint(100, size=(15, 15))

array([[95, 55, 39, 19, 75, 28, 26,  5, 10, 15, 96, 59, 30, 79, 67],
       [97, 90, 13, 20, 13, 78, 89,  7, 26, 52,  0, 58, 53, 92, 32],
       [76, 27, 25, 39, 94, 68, 43, 29,  5, 54, 62, 39, 25, 47, 83],
       [ 0, 92, 77, 53, 94, 66, 59, 57, 18, 99,  5, 73, 35,  0, 97],
       [75,  1, 26, 31, 85, 37, 37, 90, 98, 85, 76, 67, 94, 55, 26],
       [58, 44, 97, 57, 92, 94, 27, 24, 45, 29, 14, 51, 56, 59, 30],
       [48, 70, 53, 85, 86, 69,  9, 29, 22,  3, 69, 97, 89, 85, 36],
       [52, 32, 95, 37, 23, 92,  2, 69, 52, 72, 91, 38, 39, 95, 44],
       [35, 19, 59, 52, 51, 29, 29, 10, 65, 15,  0, 19, 34, 42, 28],
       [63,  6, 16, 87, 51, 28, 93, 22, 77,  5, 51, 73, 32, 43, 52],
       [87, 85, 70, 17, 59,  5, 70, 36, 63, 80, 74, 59, 75, 71, 42],
       [84,  2, 27, 41,  2, 76, 36, 53, 85, 45, 93, 14,  2, 20, 93],
       [13, 84, 44, 13, 46, 59, 93, 89, 52, 26, 54, 93, 25, 14, 91],
       [34, 47, 87, 48, 97, 52, 28, 35, 63, 47, 90,  8, 98, 35, 12],
       [70, 84, 49, 76, 22, 24, 98

In [103]:
# v)
d1 = np.repeat(5, 16)
np.diag(d1)

array([[5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5]])

7. Create a 4 x 4 square matrix with random elements from 0 to 36 then find
(i) the square of the matrix.
(ii) element by element square.
(iii) trace of the matrix.
(iv) eigenvalue of the matrix.
(v) maximum value.
(vi) minimum value.
(vii) sum of each column.
(viii) sum of each row.
(ix) product of all the elements.
(x) display 3rd row.

In [104]:
A = np.random.randint(37, size = (4, 4))
A

array([[35, 26, 24, 22],
       [26, 10, 32, 26],
       [ 0, 12, 20,  5],
       [12, 36, 15, 22]])

In [105]:
# vii) Sum of each column
[m, n] = np.shape(A)

Sum = 0

print("Finding Sum of each column:\n") 
  
# finding the column sum  
for i in range(4) : 
    for j in range(4) : 
        # Add the element  
        Sum += A[j][i] 
  
    # Print the column sum 
    print("Sum of the column",i,"=",Sum) 
  
    # Reset the sum  
    Sum = 0

Finding Sum of each column:

Sum of the column 0 = 73
Sum of the column 1 = 84
Sum of the column 2 = 91
Sum of the column 3 = 75


Similarly, one can do for the other problems as well.

# Row reduced echelon form and normal form

The rank of a matrix can be found by using `NumPy`. But to find the *Row reduced or Echelon form* of the matrices, we use `SymPy` library which is easier in this case.

In [106]:
from sympy import *
A = Matrix([[1, 1, -1, 3],
              [2, -2, 6, 8],
              [3, 5, -7, 8]
             ])
A

Matrix([
[1,  1, -1, 3],
[2, -2,  6, 8],
[3,  5, -7, 8]])

We use the command `M.rref()` to get the *Row reduced echelon form* of the matirx M

In [107]:
A1 = A.rref()
A1

(Matrix([
 [1, 0,  1,  7/2],
 [0, 1, -2, -1/2],
 [0, 0,  0,    0]]),
 (0, 1))

Observe that there is a `tuple` in the above result $A1$. To get rid of the `tuple`, we again form the same matrix $A1$ using `sympy` which helps in reducing the matrix to normal form.

In [108]:
A1 = Matrix([
 [1, 0,  1,  7/2],
 [0, 1, -2, -1/2],
 [0, 0,  0,    0]])
A1

Matrix([
[1, 0,  1,  3.5],
[0, 1, -2, -0.5],
[0, 0,  0,    0]])

We first find the `dimension` of the matrix and then reduce it to normal form using the following code.

In [109]:
[m, n] = A1.shape
for i in range(m):
    for j in range(i+1, n):
        A1[i,j] = A1[i,j] - A1[i,j]*A1[i,i]
A1

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 0, 0]])

Though `rref` cannot be achieved by `numpy`, we can reduce the `rref` matrix (obtained by using `sympy`) to normal form with the help of `numpy`. The `A1` matrix created above should be first saved as an `np.array` and `float` datatype and again use similar kind of commands. 

Observe that the algorithm/structure of the program may remain the same while the commands for different libraries differs.

In [110]:
A1 = Matrix([
 [1, 0,  1,  7/2],
 [0, 1, -2, -1/2],
 [0, 0,  0,    0]])
A1

Matrix([
[1, 0,  1,  3.5],
[0, 1, -2, -0.5],
[0, 0,  0,    0]])

In [111]:
import numpy as np
A2 = np.array(A1).astype(np.float64)
A2

array([[ 1. ,  0. ,  1. ,  3.5],
       [ 0. ,  1. , -2. , -0.5],
       [ 0. ,  0. ,  0. ,  0. ]])

In [112]:
[m, n] = np.shape(A2)
for i in range(m):
    for j in range(i+1, n):
        A2[i][j] = A2[i][j] - A2[i][j]*A2[i][i]
A2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.]])

# Establishing consistency or otherwise and solving system of linear equations.

If a given system of equations $Ax = B$ is consistent, solving it can be achieved directly by using the commands `np.linalg.inv(A).dot(B)` ($A^{-1}*B$) or `np.linalg.solve(A,B)` which is an in-built command.

Challenge is to find the consistency of the system $Ax = B$.

First we create matrices $A$ and $B$.

In [113]:
import numpy as np
A = np.array([[1, 2, -1],
    [3, -1, 2],
    [2, -2, 3]])
B = np.array([[3], [1], [2]])
[m, n] = np.shape(A)

Create an augmented matrix $[AB]$ using the command `np.column_stack(( ))`

In [114]:
AB = np.column_stack((A, B))

Find the rank of matrix $A$

In [115]:
Ra = np.linalg.matrix_rank(A)

Find the rank of augmented matrix $[AB]$

In [116]:
Rab = np.linalg.matrix_rank(AB)

Now we write theconditions

In [117]:
if Ra == Rab & Ra == n:
    print("The system is consistent and hence has Unique Solution.\n")
    print("The solution is \n")
    print(np.linalg.solve(A,B))     # We can use `np.linalg.inv(A).dot(B)` either
elif Ra == Rab & Ra != n:
    print("The system is consistent and possess infinitely many solutions.")
else:
    print("The system is inconsistent.")


The system is consistent and hence has Unique Solution.

The solution is 

[[-1.]
 [ 4.]
 [ 4.]]


In [118]:
# One more example
A = np.array([[1, -1, 1],
              [3, -1, 2],
              [3, 1, 1]])
B = np.array([[2], [-6], [-18]])
[m, n] = np.shape(A)

AB = np.column_stack((A, B))

Ra = np.linalg.matrix_rank(A)

Rab = np.linalg.matrix_rank(AB)

if Ra == Rab & Ra == n:
    print("The system is consistent and hence has Unique Solution.\n")
    print("The solution is \n")
    print(np.linalg.solve(A,B))     # We can use `np.linalg.inv(A).dot(B)` either
elif Ra == Rab & Ra != n:
    print("The system is consistent and possess infinitely many solutions.")
else:
    print("The system is inconsistent.")

The system is consistent and possess infinitely many solutions.
